name: autoflake

on:
  push:
    branches:
      - *
    exclude:
      - main
  workflow_dispatch:


jobs:
  autoflake:
    name: autoflake
    runs-on: ubuntu-latest

    steps:
      - name: install GitHub Actions@v3 actions/checkout@v3
        uses: actions/checkout@v3

      - name: install Python@latest pip@latest
        run: |
          python -m pip install --upgrade pip

      - name: install Python@latest autoflake@latest 
        run: |
          pip install autoflake \
          --force-reinstall \
          --no-clean \
          --no-color \
          --upgrade \
          --verbose

      - name: run autoflake@latest
        run: |
          autoflake \
          --in-place \
          --remove-unused-variables \
          --remove-unused-imports $(git diff --name-only HEAD^ HEAD | grep .py)

      - name: commit changes GitHub@latest
        run: |
          git config user.email "${{ github.event.head_commit.author.email }}"
          git config user.name "${{ github.event.head_commit.author.name }}"
          git commit -am "Autoformat code on commit" || true

      - name: push changes GitHub@latest
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
