name: autoflake

on:
  push:
    branches:
      - "*"
    exclude:
      - main
  workflow_dispatch:

jobs:
  autoflake:
    name: autoflake
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Install GitHub Actions@v3 actions/checkout@v3
        uses: actions/checkout@v3

      - name: Install Python@${{ matrix.python-version }} Pip@latest
        run: |
          python -m pip install --upgrade pip

      - name: Install Python@${{ matrix.python-version }} Autoflake@latest 
        run: |
          pip install autoflake \
          --force-reinstall \
          --no-clean \
          --no-color \
          --upgrade \
          --verbose

      - name: Autoflake@latest Python@${{ matrix.python-version }} 
        run: |
          autoflake \
          --in-place \
          --remove-unused-variables \
          --remove-unused-imports

      - name: GitHub@latest commit changes
        run: |
          git config user.email \
          "${{ github.event.head_commit.author.email }}"
          git config user.name \
          "${{ github.event.head_commit.author.name }}"
          git commit -am "Autoformat code on commit" || true

      - name: GitHub@latest push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
