name: black

on:
  push:
    branches:
      - "*"
    exclude:
      - main
    paths:
      - "**/*.py"

permissions:
  contents: write

jobs:
  black:
    defaults:
      run:
        shell: bash
    env:
      APP: "AnimalCrossing"
      PIP_TIMEOUT: 10
      REPOSITORY: "ApiGatewayLambdaLayer"
    environment: development
    name: black
    runs-on: ubuntu-latest
    steps:
      - name: Install Actions/Checkout@v3
        uses: actions/checkout@v3
      - name: Install Actions/Python@v3
        uses: actions/setup-python@v3
      - name: Install Python@latest/Pip@latest
        run: |
          python -m pip install pip \
          --no-color --no-input --timeout $PIP_TIMEOUT --upgrade --verbose
      - name: Install Python@latest/Black@latest
        run: |
          pip install black \
          --no-color --no-input --timeout $PIP_TIMEOUT --upgrade --verbose
      - name: Run Black@latest
        run: |
          black --no-color --verbose $(pwd)
      - name: Run GitHub@latest config user.email
        run: |
          git config user.email \
          "${{ github.event.head_commit.author.email }}"
      - name: Run GitHub@latest config user.name
        run: |
          git config user.name \
          "${{ github.event.head_commit.author.name }}"
      - name: Run GitHub@latest status
        run: |
          git status --porcelain
      - name: Run GitHub@latest commit
        run: |
          git commit -am "Autoformatting (${{ github.ref }})"
      - name: Run GitHub@latest push ${{ github.ref }} ${{ github.event.head_commit.author.name }}
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_with_lease: true
