name: deployment

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deployment:
    environment: production
    name: deployment
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: install GitHub Actions@v3 actions/checkout@v3
        uses: actions/checkout@v3

      - name: install Terraform@v1 hashicorp/setup-terraform@v1
        uses: hashicorp/setup-terraform@v1
      
      - name: install Python Pip@latest
        run: python -m pip install --upgrade pip
