name: pip-install-dependencies

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  pip-install-dependencies:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: pip-install
        run: |
          pip install -r requirements.txt -t . --no-user
