name: pip

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  install-dependencies:
    environment: production
    name: install-dependencies
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
