name: pylint

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pylint:
    defaults:
      run:
        shell: bash
    env:
      APP: "AnimalCrossing"
      PIP_TIMEOUT: 10
      RESOURCE: "ApiGateway"
      SERVICE: "LambdaLayer"
    environment: development
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - name: Install Actions/Checkout@v3
        uses: actions/checkout@v3
      - name: Install Actions/Python@v3
        uses: actions/setup-python@v3
      - name: Install Python@latest/Pip@latest
        run: |
          python -m pip install pip \
          --no-color \
          --no-input \
          --timeout $PIP_TIMEOUT \
          --upgrade \
          --verbose
      - name: Install Python@latest/Pylint@latest
        run: |
          pip install pylint \
          --no-color \
          --no-input \
          --timeout $PIP_TIMEOUT \
          --upgrade \
          --verbose
      - name: Run Pylint@latest
        run: |
          pylint \
          --disable=C0114,C0103,W1203,W0611,W0703 \
          --ignore=tests \
          --max-line-length=120 \
          **/*.py
