name: pylint

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pylint:
    name: pylint
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Install GitHub Actions@v3 actions/checkout@v3
        uses: actions/checkout@v3

      - name: Install Python@${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python@${{ matrix.python-version }} Pip@latest
        run: |
          python -m pip install --upgrade pip

      - name: Install Python@${{ matrix.python-version }} Pylint@latest 
        run: |
          pip install pylint \
          --force-reinstall \
          --no-clean \
          --no-color \
          --upgrade \
          --verbose

      - name: Pylint@latest Python@${{ matrix.python-version }} 
        run: |
          pylint $(git ls-files '*.py')
