name: terraform

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    environment: production
    name: deployment
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: install GitHub Actions@v3 actions/checkout@v3
        uses: actions/checkout@v3

      - name: install Terraform@v1 hashicorp/setup-terraform@v1
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: run Terraform@v1 init
        run: |
          terraform init \
          -backend=false \
          -input=false \
          -no-color \
          -reconfigure

      - name: run Terraform@v1 fmt
        run: |
          terraform fmt \
          -check \
          -list=false \
          -no-color \
          -recursive \
          -write=false
