name: terraform

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    environment: production
    name: deployment
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      TERRAFORM_BACKEND: terraform-backend.sh

    steps:
      - uses: actions/checkout@v3

      - name: terraform-setup
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

        run: |
          cat <<EOF >$TERRAFORM_BACKEND.tf
          terraform {
            backend "s3" {
              bucket = "${{ secrets.AWS_ACCOUNT_ID }}"
              key    = "AnimalCrossing/ApiGatewayLambdaLayer/terraform.tfstate"
              region = "${{ secrets.AWS_DEFAULT_REGION }}"
            }
          }
          EOF

      - name: terraform-backend-permission
        run: |
          chmod +x ./$TERRAFORM_BACKEND.tf

      - name: terraform-init
        run: |
          terraform init \
          -input=false -reconfigure -no-color

      - name: terraform-fmt
        run: |
          terraform fmt \
          -check -no-color -recursive

      - name: terraform-plan
        run: |
          terraform plan \
          -compact-warnings -detailed-exitcode -input=false -no-color
          -var account="${{ secrets.AWS_ACCOUNT_ID }}"
          -var region="${{ secrets.AWS_DEFAULT_REGION }}"
