name: terraform

on:
  push:
    branches:
      - "*"
    exclude:
      - main
    paths:
      - "**/*.tf"

permissions:
  contents: write

jobs:
  terraform:
    defaults:
      run:
        shell: bash
    env:
      APP: "AnimalCrossing"
      RESOURCE: "ApiGateway"
      SERVICE: "LambdaLayer"
    environment: development
    name: black
    runs-on: ubuntu-latest
    steps:
      - name: Install Actions/Checkout@v3
        uses: actions/checkout@v3
      - name: Install Actions/Python@v3
        uses: actions/setup-python@v3
      - name: Install Terraform@latest
        uses: hashicorp/setup-terraform@v1
      - name: Run Terraform@latest initalize
        run: |
          terraform init \
          -backend=false -input=false -no-color -reconfigure
      - name: Run Terraform@latest format
        run: |
          terraform fmt \
          -list=true -no-color -recursive -write=true
      - name: Run GitHub@latest config user.email
        run: |
          git config user.email \
          "${{ github.event.head_commit.author.email }}"
      - name: Run GitHub@latest config user.name
        run: |
          git config user.name \
          "${{ github.event.head_commit.author.name }}"
      - name: Run GitHub@latest status
        run: |
          git status
      - name: Run GitHub@latest status check
        run: echo $(git status --porcelain | grep -q "M\|A\|D\|R\|C" && echo 0 || echo 1)
      - name: Run GitHub@latest commit
        if: success()
        run: |
          git commit -am "Autoformatting (${{ github.ref }})"
      - name: Run GitHub@latest push ${{ github.ref }} ${{ github.event.head_commit.author.name }}
        if: success()
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_with_lease: true
